# Generated by Django 4.1.7 on 2023-03-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\t)'), (' ', 'Space ( )'), ('|', 'Pipe (|)')], default=',', max_length=5)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], default='"', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('rows', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[(0, 'In process'), (1, 'Ready')], max_length=15)),
                ('download_link', models.URLField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('type', models.IntegerField(choices=[(0, 'Full name'), (1, 'Job'), (2, 'Email'), (3, 'Domain name'), (4, 'Phone number'), (5, 'Company name'), (6, 'Text'), (7, 'Integer'), (8, 'Address'), (9, 'Date')])),
                ('order', models.IntegerField(blank=True, default=0)),
                ('range_from', models.IntegerField(blank=True, null=True)),
                ('range_to', models.IntegerField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schema')),
            ],
        ),
    ]
